config:
  emsa:deployType: app
  emsa:sshKeyName: emsa
  emsa:domain: emsa.mk
  emsa:pulumiOrg: emsamacedonia-yahoo-com
  emsa:dbPassword:
    secure: AAABACrUTqz1DLZmoUCeV0ZpZMS9kIWOe4TeTm671f1ON1SJ4aZ3kezHS7N27+it
  emsa:jwtSecret:
    secure: AAABAJFB8vuqPtJith14x82THUiSlUJO9hu6uxIDUcsAwDVkD2yRt64mIM/gzw3NqZiwO40sL4IVxIvpa4xwBvyqucghqi/3c+ce
  emsa:googleClientId:
    secure: AAABAEZBjkl1jHFZiQOTzXRa6pnDzomxqecjip8qkxnQk0g74bvtI4pa+l99nacLCQ3rVcX0LwkKIP5gFqrjig0+j/voSJ88KX/waPq6grz5aaGwTjabB+9MEsAtRumicJhxeFEcS+s=
  emsa:googleClientSecret:
    secure: AAABAGNJV+J1Gi5MWMGr1+u418SWoxqXbyeWa2fVPM7S6QaBJFGCiGyAFtSuW11V0/nfmnTF9QbJwsO3hJlR6FQL8Q==
  emsa:resendApiKey:
    secure: AAABAJOegY4cZSodU/PzB+go+GDuVmA+lsVVJBsjU/ErmJjTFrIbPHDhQzOOMloZSJDkNhG2HoRR3Pq8TWzjnthfCyY=
  emsa:fromEmail: noreply@emsa.mk
  emsa:r2AccessKeyId:
    secure: AAABAI80474TvXEqF/UboXmjoPRvaTq/pMS/5QKz4vx4OEjRViZf9P8a9Vn4Ob1aUrgv/IKI3G+Fni6LZ1FhWA==
  emsa:r2SecretAccessKey:
    secure: AAABAIJKxQmgl2KgObEQ+tWR6DFf50EHjS9vMIsd4cadRG042LIcpW/kQOkdJ387IYrD6YDNEs6BGq46juXVpBWjfIFRL6EkUcyrLhjXmeM469K+fjXqcuKVW1lSC94x
  emsa:r2AccountId:
    secure: AAABAGLkxPkygNuw71gIPKoSo8f3Lrd2axy0ziYZo//i+kbuH6yzi8oMDk0CIC7UFkctT+SqrS2ktayE14UbjQ==
  emsa:r2Bucket: emsa-prod
  emsa:r2PublicUrl: https://pub-0fbc8427d56641c4be3571aa909201bf.r2.dev
