export const PageRoutes = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  ADMIN: "/admin",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_DASHBOARD_SEGMENT: "dashboard",
  ADMIN_USERS: "/admin/users",
  ADMIN_USERS_SEGMENT: "users",
  ADMIN_PILLARS: "/admin/pillars",
  ADMIN_PILLARS_SEGMENT: "pillars",
  ADMIN_PROJECTS: "/admin/projects",
  ADMIN_PROJECTS_SEGMENT: "projects",
  ADMIN_ORGANIZATION: "/admin/organization",
  ADMIN_ORGANIZATION_SEGMENT: "organization",
  PROFILE: "/profile",
  UNAUTHORIZED: "/unauthorized",
  AUTH_CALLBACK: "/auth/callback",
} as const;

export const ApiRoutes = {
  AUTH_REGISTER: "/api/auth/register",
  AUTH_LOGIN: "/api/auth/login",
  AUTH_LOGOUT: "/api/auth/logout",
  AUTH_GOOGLE: "/api/auth/google",
  AUTH_GOOGLE_CALLBACK: "/api/auth/google/callback",
  ADMIN_USERS: "/api/admin/users",
  ADMIN_USER_BY_ID: "/api/admin/users/:id",
  ADMIN_PILLARS: "/api/admin/pillars",
  ADMIN_PILLAR_BY_ID: "/api/admin/pillars/:id",
  ADMIN_PROJECTS: "/api/admin/projects",
  ADMIN_PROJECT_BY_ID: "/api/admin/projects/:id",
  ADMIN_PROJECTS_UPLOAD: "/api/admin/projects/upload",
  ADMIN_DASHBOARD: "/api/admin/dashboard",
  ADMIN_ORGANIZATION: "/api/admin/organization",
  ADMIN_ORGANIZATION_UPLOAD: "/api/admin/organization/upload",
  ORGANIZATION: "/api/organization",
  USERS_ME: "/api/users/me",
  UPLOAD_PRESIGNED: "/api/upload/presigned",
} as const;
